name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    if: contains(toJson(github.event.commits), 'Automated publish') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      - name: Generate README
        run: bash .github/update_readme.sh > README.md
      - name: Commit and Push README.md 
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH_NAME: 'main'